#Faça um programa que leia algo pelo teclado e mostre na tela seu tipo de dado e todas as informações sobre
#ele
a = input("digite algo: ")
print(a.islower)
print(a.isupper)
print(a.isnumeric)
print(a.isalnum)
print(a.isalpha)
print(a.isascii)
print(a.isdecimal)
print(a.isdigit)
print(a.isidentifier)
print(a.isprintable)
print(a.isspace)
print(a.istitle)